---
- hosts: all
  roles:

  # osx config
  # - role: dock
  #   apps:
  #   - /Applications/Firefox.app
  #   - /Applications/Airmail.app
  #   - /Applications/Dashlane.app
  #   - /Applications/Spotify.app
  #   - /Applications/Airmail.app
  #   - "/Applications/Adobe Photoshop CC/Adobe Photoshop CC.app"
  #   - "/Applications/Adobe Illustrator CC/Adobe Illustrator.app"
  #   - /Applications/Atom.app
  #   - /Applications/iTerm.app
  #   - /Applications/Dash.app
  #   folders:
  #   - path: ~/
  #   - path: ~/Documents
  #   - path: ~/Downloads
  #     sort: datemodified
  # - role: cask_package
  #   package_name: asepsis
  # - role: dashboard
  #   disabled: YES

  # repos
  - role: git_package
    repo: github.com/jeanregisser/dotfiles update=no
  - role: git_package
    repo: github.com/zsh-users/antigen
  - role: git_package
    repo: github.com/mitmproxy/mitmproxy
  - role: git_package
    repo: github.com/facebook/chisel
  - role: git_package
    repo: github.com/square/PonyDebugger recursive=no

  # cli
  # shell tooling
  - role: spf13_vim
  - role: rbenv
    global: '2.1.2'
    rubies: 
    - '2.1.0'
    - '2.1.1'
    - '2.1.2'
    - 'rbx-2.2.6'

  tasks:
  - include: brews.yml
  - include: casks.yml
  - include: gems.yml
  - include: npm_packages.yml
  - include: pip_packages.yml

